### ISSUE TITLE
Testing notion-sdk-py when part of another project

### ISSUE THREAD

**Issue by thomashirtz** [ramnes/notion-sdk-py#108]
Hello,
I am using notion-sdk-py for a project, I would like to write tests in order to see if the different functions that are using some modules from notion-sdk-py are working in order to enhance the workflow/stability of my project. However I am not sure how it is possible to test this API as it is linked to a notion database/account. 
Do you have recommendation on how to do so ? 
Thanks!

**Comment by ramnes** [comment]
The most common method in that kind of scenario is to mock the library completely. Another solution is to use cassettes, just as we're doing in notion-sdk-py (instead of mocking httpx). It requires a test account or a template page for when you're writing new tests or updating the API calls made in previous tests, but the good point is that the rest of the time, i.e. when anyone just change a few things, all the API calls are perfectly mocked without effort.

**Comment by thomashirtz** [comment]
What do you mean by mock the library completely ?
So it means that every time you make changes to this library, you'll use an account to test that notion-sdk-py is working ? You save this account credential locally and test only locally ? I was trying to learn good practices and implement all that on my github but I'm not sure there is an easy and clean way to do this then :/

**Comment by ramnes** [comment]
> What do you mean by mock the library completely ?

Monkey patching the library during the tests so that it returns what you assume it would always return in your scenarios, so that you can run the test without an API key.

The basic way to do this is with [`unittest.mock`](https://docs.python.org/3/library/unittest.mock.html). Then you have a lot of higher-level wrappers, e.g. [pytest-mock](https://github.com/pytest-dev/pytest-mock).

> So it means that every time you make changes to this library, you'll use an account to test that notion-sdk-py is working ? 

Only when I write new tests that call the API, or change the calls of an existing test.

> You save this account credential locally and test only locally ?

The API key is passed through the environment ([12 factors](https://12factor.net/) style). Tests are run both locally and through CI with the cassettes. But real API calls to generate the cassettes are only made locally.

> I was trying to learn good practices and implement all that on my github but I'm not sure there is an easy and clean way to do this then :/

There's only so much you can do when depending on a tier API you don't have any control over. I wish Notion's team would release a fake API server à la [localstack](https://github.com/localstack/localstack) but I don't see that coming soon and I'm not sure I want to do it myself either. :)

**Comment by thomashirtz** [comment]
Ok thank you for your detailed answer :) !

> There's only so much you can do when depending on a tier API you don't have any control over. I wish Notion's team would release a fake API server à la [localstack](https://github.com/localstack/localstack) but I don't see that coming soon and I'm not sure I want to do it myself either. :)

Understandable haha
