### ISSUE TITLE
notion_client.errors.APIResponseError: This API is deprecated when trying to fetch databases

### ISSUE THREAD

**Issue by deepaerial** [ramnes/notion-sdk-py#132]
When trying to list databases I get `notion_client.errors.APIResponseError: This API is deprecated when trying to fetch databases` exception: 
```python
import os
from notion_client import Client

notion = Client(auth=os.getenv("NOTION_SECRET"))
databases = notion.databases.list()  # raises notion_client.errors.APIResponseError exception
```
`pytest` log:
```
self = <notion_client.client.Client object at 0x10a38ce80>, response = <Response [400 Bad Request]>

    def _parse_response(self, response: Response) -> Any:
        try:
            response.raise_for_status()
        except httpx.HTTPStatusError as error:
            try:
                body = error.response.json()
                code = body.get("code")
            except json.JSONDecodeError:
                code = None
            if code and is_api_error_code(code):
>               raise APIResponseError(response, body["message"], code)
E               notion_client.errors.APIResponseError: This API is deprecated.
```

* Python: 3.9.9
* notion-client version: `1.0.0`

Library was installed using `poetry` with:
```shell
$ poetry add notion-client
```

**Comment by ramnes** [comment]
Hey @deepaerial, sorry for not answering sooner.

Yes, the endpoint is deprecated, and it's even written in our docs: https://github.com/ramnes/notion-sdk-py/blob/cd7df5705ee88bcb962facc06df2547b2d6f0b68/notion_client/api_endpoints.py#L116

I don't want to remove the method because some people might still use it with an older `Notion-Version` header.

How could we have a smoother developer experience, in your opinion?

**Comment by deepaerial** [comment]
@ramnes I'm not sure for now , but I think it would be useful to add some documentation with basic usage examples. In the docs you can also provide link to official Notion API documentation.

**Comment by ramnes** [comment]
We do both actually!
