### ISSUE TITLE
notion_client does not work in a class under multiprocessing

### ISSUE THREAD

**Issue by everping** [ramnes/notion-sdk-py#203]
When I initiated this notion module as a property of a class and then ran the class as `multiprocessing`, I got

```
TypeError: cannot pickle '_thread.RLock' object
```

My code
```python
from multiprocessing import Pool

from notion_client import Client

NOTION_TOKEN = 'secret_12343'


class Task:
    def __init__(self):
        self.notion = Client(auth=NOTION_TOKEN)

    def run(self):
        print(1)


def run(task):
    task.run()


if __name__ == '__main__':
    tasks = [Task()]

    with Pool(processes=len(tasks)) as executor:
        executor.map(run, tasks)
```

I fixed that by moving the declaration of `self.notion` to the outside of the Class
```python
...
notion = Client(auth=NOTION_TOKEN)

class Task:
...
```

or

```python
...
class Task:
    def __init__(self):
        notion = Client(auth=NOTION_TOKEN)
...
```

Can you explain this problem?

**Comment by ramnes** [comment]
I can't help on the usage of the `multiprocessing` library because I've almost never used it.

That being said, you get this error because the library is trying to pickle your `Client` instance (because it pickles the `Task` instance in the first place, I guess), most likely so that it can be passed between processes. Notion clients aren't meant to be passed between processes or even pickled, and you'd have the exact same with something like `httpx.Client` for example.

Do you have a good reason to pass the client between processes in particular (i.e. your first example), rather than defining a global context client that will get forked (i.e. your second example)?

**Comment by ramnes** [comment]
Going ahead and closing this one, but feel free to comment if this is still an issue and have more context to give.
