### ISSUE TITLE
iterate_paginated_api and api_endpoints#query seems to be broken in 2.2.0

### ISSUE THREAD

**Issue by SCORE1387** [ramnes/notion-sdk-py#224]
Hello, thank you for this awesome library!

In my code I'm using
`iterate_paginated_api(self.__notion.databases.query, database_id=self.__db_id, filter=db_filter)` and starting from version 2.2.0 I face two problems:
1. Previously there was no error thrown if `db_filter=None`, but now there is `body failed validation: body.filter should be an object or undefined, instead was null.` error.
It's probably caused by this change and the fact that `base[key] is not None` check is now gone.
![image](https://github.com/ramnes/notion-sdk-py/assets/2854008/c2de93bc-6455-4efa-a235-d8c36e17817e)
3. This code is stuck in a never-ending loop returning a list of DB items from 0 to 99 and never gets to the next portion.
This is also probably caused by the change in `pick` function - `start_cursor` argument is not picked e.g. for query function anymore https://github.com/ramnes/notion-sdk-py/blob/577ad9d326877d61690e5dcad6f49d4f25e3b38c/notion_client/api_endpoints.py#L136

**Comment by HorsenLi** [comment]
I meet the same problem

**Comment by ramnes** [comment]
Hey Sergey, thanks for the kind words and for the issue.

> Previously there was no error thrown if db_filter=None, but now there is body failed validation: body.filter should be an object or undefined, instead was null. error.

The error with `None` is intentional: some fields are actually meant to receive `None` as a value, e.g. if you want to remove an icon from a page, so we have to pass the `None` values. Since Python doesn't have such a thing as `undefined`, you have to avoid passing a `None` value that you don't want the API to receive. :)

I'd recommend to modify your code with something such as:

```python
query = {"database_id=self.__db_id"}
if db_filter:
    query["filter"] = db_filter
iterate_paginated_api(self.__notion.databases.query, **query)
```

Does it sound reasonable to you?

> This code is stuck in a never-ending loop returning a list of DB items from 0 to 99 and never gets to the next portion

Good catch, thanks! Fix and release incoming.

**Comment by ramnes** [comment]
>> This code is stuck in a never-ending loop returning a list of DB items from 0 to 99 and never gets to the next portion
>
> Good catch, thanks! Fix and release incoming.

Released. Can you try 2.2.1?

**Comment by SCORE1387** [comment]
All good now, thanks for a quick reaction!
