### ISSUE TITLE
Implement error handling

### ISSUE THREAD

**Issue by ramnes** [ramnes/notion-sdk-py#7]

**Comment by ramnes** [comment]
When it's done, we'll call .json() on all responses so that it's one thing less to type. We can't do it yet because we don't have a way to check for the status code otherwise, but if we handle errors, there is no need to do that check anymore.

**Comment by Blue-Hope** [comment]
@ramnes here's my fix on errors so that we can return .json() safely without any httpx / api exception
https://github.com/ramnes/notion-sdk-py/pull/14
We have an issue about enum class on python, the enum value is returned like `APIErrorCode.ObjectNotFound.value`
so we maybe make fix on
```
except APIResponseError as error:
    if error.code == APIErrorCode.ObjectNotFound:
        ...  # For example: handle by asking the user to select a different database
    else:
        # Other error handling code
        logging.exception()
```
to 
```
except APIResponseError as error:
    if error.code == APIErrorCode.ObjectNotFound.value:
        ...  # For example: handle by asking the user to select a different database
    else:
        # Other error handling code
        logging.exception()
```

or ensure that error.code is type <enum: "APIErrorCode">, not str

**Comment by ramnes** [comment]
Awesome! See my comments on your PR.

> or ensure that error.code is type <enum: "APIErrorCode">, not str

I'd rather go this way!
